name: Release to Nucleus

on:
  release:
    types: [ published ]

jobs:
  bump-pyproject-version:
    name: Bump pyproject version
    runs-on: ubuntu-latest

    steps:
      - name: Get token for GitHub App
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v3
        with:
          application_id: ${{ secrets.GH_APP_ID }}
          application_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
    
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ steps.get_workflow_token.outputs.token }} 

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.8.3"

      - name: Bump the version
        run: poetry version ${{ github.event.release.tag_name }}

      - name: Commit changes using GitHub App
        run: |-
          git config user.name 'devlarabar[bot]'
          git config user.email '198984901+devlarabar[bot]@users.noreply.github.com'
          git add .
          git commit -m "Automated commit by GitHub App"
          git push
