name: Write to README

on:
  release:
    types: [ published ]

jobs:
  write-to-readme:
    name: Write to README.md
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # Set up the GitHub App authentication
      - name: Generate GitHub App JWT Token
        id: generate-jwt
        uses: peter-evans/github-app-token@v2
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      
      # Set up the GitHub App token in the Git configuration
      - name: Set up GitHub App commit signer
        run: |
          git config --global user.name "devlarabar"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global commit.gpgSign true

      - name: Write to README.md
        run: |
          echo '${{ github.event.release.tag_name }}' >> README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: README.md
          commit_message: Append version ${{ github.event.release.tag_name }} to README.md
