name: Write to README

on:
  release:
    types: [ published ]

jobs:
  write-to-readme:
    name: Write to README.md
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Write to README.md
        run: |
          echo '${{ github.event.release.tag_name }}' >> README.md

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: README.md
          commit_message: Append version ${{ github.event.release.tag_name }} to README.md
